### PR TITLE
ss24 updated slides

### PR DESCRIPTION
**Pull request by pallaviaithalnarayan**

### CODE REVIEW

**Comment by pallaviaithalnarayan** [comment]
I have added new slides under materials, kindly review and merge the request.

**Review by alex-mitrevski — CHANGES_REQUESTED** [review]
@pallaviaithalnarayan A couple of things before we merge:
* Remove the .DS_Store file
* Rename the "Name (1)" files so that the names are more meaningful
* Add the notebooks in "calculus_notebooks.zip" directly (i.e. not as a zip archive)

**Comment by pallaviaithalnarayan** [comment]
@alex-mitrevski I have made the changes, please review them once.

**Comment by alex-mitrevski** [comment]
@pallaviaithalnarayan The .DS_Store file is still there...

**Comment by pallaviaithalnarayan** [comment]
@alex-mitrevski It was hidden in my local repo, now added it in gitignore.

**Comment by alex-mitrevski** [comment]
@pallaviaithalnarayan You need to add `*.DS_Store`, otherwise it's not ignored in subdirectories. `materials/.DS_Store` is still there and needs to be removed with a commit.

**Review by alex-mitrevski — APPROVED** [review]

**Comment by alex-mitrevski** [comment]
@pallaviaithalnarayan It's good now, I've merged. Thanks!

**Pull request merged**
